services:
  bot:
    build:
      context: .
      dockerfile: conf/bot/Dockerfile
    restart: unless-stopped
    environment:
      SHPAGA_POSTGRES_DSN: "host=db user=shpaga password=shpaga dbname=shpaga port=5432 sslmode=disable"
      SHPAGA_TELEGRAM_TOKEN: "${SHPAGA_TELEGRAM_TOKEN}"
      SHPAGA_CTFTIME_CLIENT_ID: "${SHPAGA_CTFTIME_CLIENT_ID}"
      SHPAGA_CTFTIME_CLIENT_SECRET: "${SHPAGA_CTFTIME_CLIENT_SECRET}"
      SHPAGA_CTFTIME_REDIRECT_URL: "${SHPAGA_CTFTIME_REDIRECT_URL}"
  
  api:
    build:
      context: .
      dockerfile: conf/api/Dockerfile
    restart: unless-stopped
    environment:
      SHPAGA_POSTGRES_DSN: "host=db user=shpaga password=shpaga dbname=shpaga port=5432 sslmode=disable"
      SHPAGA_TELEGRAM_TOKEN: "${SHPAGA_TELEGRAM_TOKEN}"
      SHPAGA_CTFTIME_CLIENT_ID: "${SHPAGA_CTFTIME_CLIENT_ID}"
      SHPAGA_CTFTIME_REDIRECT_URL: "${SHPAGA_CTFTIME_REDIRECT_URL}"
    ports:
      - "80:8080"
  
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: shpaga
      POSTGRES_PASSWORD: shpaga
      POSTGRES_DB: shpaga
    volumes:
      - ./vol/db/data:/var/lib/postgresql/data
